### ISSUE TITLE
How complete is this interface?

### ISSUE THREAD

**Issue by deepak07** [jschroeder9000/clam_scan#2]
I am planning to use clamav for scanning uploaded files and was planning to create a ruby wrapper for clamav command line utilities. On searching I found your gem. 
So I wanted to know how complete is your gem and are you planning to maintain this repository further.

**Comment by jschroeder9000** [comment]
You should be able to do anything with this gem that you could do with clamscan/clamdscan cli.  If you find something missing, please let me know.  I am using it in production, so I intend to maintain it for the foreseeable future.

I originally wrote this when I couldn't find a similar gem that suited my needs.  Clamby (which I see you've also found) was closest and I originally planned to modify it and submit a pull request, but after doing that I had already touched most of the code so I decided to just rewrite the rest of it and release a separate gem.

Probably the biggest difference is that this gem supports and validates any arguments you can pass to clamscan/clamdscan in a rubyish way.  So where you might call `clamscan --recursive --max-recursion=5 /path/to/dir` via cli, with this gem you can call `ClamScan::Client.scan(location: '/path/to/dir', recursive: true, max_recursion: 5)` with this gem (see readme).

One of the biggest issues I had with clamby (in addition to not supporting custom arguments) was that it [doesn't escape shell arguments](https://github.com/kobaltz/clamby/blob/7df2f696b1406f1917b4d2259506279fc3c57962/lib/clamby.rb#L28).  Looks like I never created an issue for that there... [I have now done so](https://github.com/kobaltz/clamby/issues/3) so that may change in the future.

**Comment by deepak07** [comment]
Thanks for the detailed feedback. I have decided to go with your gem and will let you know if an issues comes up.
